language: node_js

env:
  - FORCE_COLOR=true

node_js:
  - 10.12
  - 12
  - node

jobs:
  include:
    - stage: release
      if: branch = master AND type != pull_request
      node_js: 12
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
